### ISSUE TITLE
Simple text file (XML / CSV) import / export?

### ISSUE THREAD

**Issue by hmeine** [ramonpoca/ColorTools#11]
I would be interested in a text-based format (XML, CSV, ...) for import / export, which would be easier to process with scripts, and sync with e.g. LaTeX, Gimp and so on.

**Comment by dfernandez79** [comment]
+1 to that :)

**Comment by hmeine** [comment]
[HTML2CLR](https://github.com/ramonpoca/ColorTools#html2clr) seems to be half-way there.  It just lacks a way to specify the names, and an opposite variant (i.e. CLR2HTML, if you want to keep that naming scheme, although only the RGB code has the HTML syntax).
