### ISSUE TITLE
"My Kuler Theme" as swatch folder name in Adobe

### ISSUE THREAD

**Issue by gyansantokhi** [ramonpoca/ColorTools#15]
Could this be changed into the basename of the file so adding multiple .ase files will automatically be organized in a recognizable folder structure?

Thanks for these wonderful tools!

**Comment by ramonpoca** [comment]
What do you mean?

**Comment by gyansantokhi** [comment]
<img width="254" alt="screen shot 2015-08-29 at 16 05 16" src="https://cloud.githubusercontent.com/assets/11832986/9562255/db29f676-4e67-11e5-8f64-4d2208d6e4c5.png">
My file is called StatenGeneraal.ace and is imported as StatenGeneraal, however all the swatches are grouped under "My Kuler Theme". Could either the groupname be changed into the filename or instead not have a group name at all?
