### ISSUE TITLE
Generating .clr seems incorrect

### ISSUE THREAD

**Issue by seejamescode** [ramonpoca/ColorTools#18]
Hi there,

I have used both html2clr and json2clr. Both take inputs, but have the same, incorrect results for Keynote.

Here are the values:
#6AEBF4 -> #5DE8F1
#FED500 -> #FDCE0A

Is the script, keynote, or a setting the problem?

**Comment by ramonpoca** [comment]
The colors are imported, by default, in the sRGB colorspace. The values you are seeing in the color picker are in the "RGB Generic" colorspace. If you click in the gear icon right from the "RGB sliders" selector, you can select the target colorspace. In sRGB you'll see that the hex values match.
