### ISSUE TITLE
Incorrect hex value after using Ase2Clr tool

### ISSUE THREAD

**Issue by nefaurk** [ramonpoca/ColorTools#20]
Steps to reproduce:
1. Create a swatch with the following hex value in Illustrator: #730000
2. Export your swatch as an ASE file
3. Run Ase2Clr
4. Install the CLR file in ~/Library/Colors
5. Open the color picker in TextEdit and select the color you just installed
6. Notice that the hex value for the color isn't accurate

<img width="674" alt="1" src="https://user-images.githubusercontent.com/68014/27704937-46479ce2-5cda-11e7-8575-921c608e10d8.png">
<img width="437" alt="2" src="https://user-images.githubusercontent.com/68014/27704940-47db8a1e-5cda-11e7-957d-33d0ea9570fd.png">

![3](https://user-images.githubusercontent.com/68014/27709148-0dda7f46-5ce9-11e7-8d84-831ed0043814.png)

![4](https://user-images.githubusercontent.com/68014/27709155-0fc84504-5ce9-11e7-8bdf-2cba3d023ff1.png)

**Comment by ramonpoca** [comment]
Check on the second tab (RGB Picker), that you are in the sRGB colorspace (the gear icon).
