### ISSUE TITLE
Color profile

### ISSUE THREAD

**Issue by RaphyRaph** [ramonpoca/ColorTools#4]
Would there be a way to set a color profile when converting color swatches? Right now it defaults to generic RGB but I'd like to set it to sRGB.

**Comment by ramonpoca** [comment]
In which tool? SwatchInstall or the command line ones?

**Comment by RaphyRaph** [comment]
SwatchInstall

**Comment by ramonpoca** [comment]
ASE files come with no colorspace information, so we assume generic. You can patch Ase2Clr/RPCAdobeSwatchExchange.m:69 to use a different NSColor constructor (like it's done for the CMYK values, for example).

**Comment by RaphyRaph** [comment]
I tried to get in there and apply a sRGB color space it to the html2clr command and build it, but I failed because my coding skills are limited. Do you think you could share a version of html2clr that applies the sRGB color space?

**Comment by ramonpoca** [comment]
You just have to patch ColorTools/Html2Clr/NSColor+Hexadecimal.m:58
Replace `colorWithRed` by `colorWithSRGBRed` and build.

**Comment by RaphyRaph** [comment]
Cool thx!!

**Comment by RaphyRaph** [comment]
Doesn't seem to work. Just defaults to generic rgb.
![screen shot 2015-01-27 at 12 40 57 pm](https://cloud.githubusercontent.com/assets/3810802/5926764/69a861f6-a622-11e4-9d57-7e066b1fe35d.png)

**Comment by ramonpoca** [comment]
That's your colorpicker working space, not the palette. If you change it you'll see the values of red, green and blue change to the selected colorspace.
For example, set to sRGB, select r=40,g=40,b=40. Then change to Generic RGB and you'll see the values change to (30,30,30).

So sRGB(40,40,40) = GenericRGB(30,30,30).
If your origin palette is in a sRGB colorspace and has #282828 (40,40,40), and you import it with the modified html2clr, it will show as (30,30,30) on the Generic RGB colorspace.

**Comment by RaphyRaph** [comment]
Got it. Then, how do I export a sRGB palette?


—
Raphaël

**Comment by ramonpoca** [comment]
What are you trying to do?

**Comment by RaphyRaph** [comment]
I'm trying to export a set of hex values into a .clr file where the RGB
values are set as sRGB by default.

**Comment by ramonpoca** [comment]
If your origin hex values are COORDINATES IN THE sRGB COLORSPACE, and you import them as sRGB values (with the patched version of html2clr, creating the UIColor over the sRGB colorspace), then the colors in the .clr file will point the same perceptual color.
Do you see a disparity between the hex coordinates and the loaded colors?
