### ISSUE TITLE
Uncought Exception

### ISSUE THREAD

**Issue by Designscheu** [ramonpoca/ColorTools#5]
I tried to convert an ase to cld with the command line tool and get the following error:

Version 1.0, blocks 12
2015-02-20 15:57:36.276 Ase2Clr[8217:26756334] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** invalid number of components for colorspace in initWithColorSpace:components:count:'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff93d9e66c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9604c76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff93d9e51d +[NSException raise:format:] + 205
	3   AppKit                              0x00007fff8d05fb5e -[NSColorSpaceColor initWithColorSpace:components:count:] + 213
	4   AppKit                              0x00007fff8d05f9b9 +[NSColor colorWithColorSpace:components:count:] + 29
	5   Ase2Clr                             0x000000010c8621fb -[RPCAdobeSwatchExchange readBlock:] + 1074
	6   Ase2Clr                             0x000000010c861d75 -[RPCAdobeSwatchExchange readFromFile:toColorListNamed:] + 485
	7   Ase2Clr                             0x000000010c863406 main + 315
	8   libdyld.dylib                       0x00007fff9a9745c9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by ramonpoca** [comment]
Can you check if master version fixes your problem?

**Comment by Designscheu** [comment]
Hi,
the build from the master works. Thanks.
