### ISSUE TITLE
[xibcolor] Alpha support

### ISSUE THREAD

**Issue by kenji21** [ramonpoca/ColorTools#6]
Hello,

Had to manage change from a ARGB color to another ARGB one, but the script only manage RGB :

    <color key="backgroundColor" red="0.32148650288581848" green="0.045969739556312561" blue="0.072000645101070404" alpha="0.73333334922790527" colorSpace="calibratedRGB"/>

But no alpha management yet in the script (and I'm not knowing python enought to make a PR).

**Comment by ramonpoca** [comment]
Can you check if every color in your XML has alpha component? It would be just a case of adding this component standard.

**Comment by kenji21** [comment]
In fact, I don't want to change the alpha this time.
As you keep the key="", I think the script is OK for this usage.

I think alpha is always here :

    $ find . -name *.xib -exec grep "<color" {} \; |wc -l
     250
   $ find . -name *.xib -exec grep "<color" {} \; | grep -v alpha | wc -l
       0

**Comment by kenji21** [comment]
On a little more projects :

    ~/source-cache $ find . -name *.xib -exec grep "<color" {} \; | grep calibrated | grep alpha | wc -l
    4752
    ~/source-cache $ find . -name *.xib -exec grep "<color" {} \; | grep calibrated | wc -l
    4752

**Comment by ramonpoca** [comment]
I have pushed a quick-and-dirty modification, supporting #rrggbbaa format for alpha. Can you give it a try?

**Comment by kenji21** [comment]
Look good, but I prefer having AARRGGBB codes. As you have done it in NSColor+Hexadecimal :

      case 8: // #AARRGGBB
        alpha = [self colorComponentFrom:colorString start:0 length:2];
        red = [self colorComponentFrom:colorString start:2 length:2];
        green = [self colorComponentFrom:colorString start:4 length:2];
        blue = [self colorComponentFrom:colorString start:6 length:2];
        break;

**Comment by kenji21** [comment]
So I can copy paste from diff of the colors.txt file we have in version control.

**Comment by ramonpoca** [comment]
Yup, ARGB seems to be more "standard".
I've pushed another change to use ARGB. Please test it.

**Comment by kenji21** [comment]
You have forgot a rgbatohex call :

     NameError: global name 'rgbatohex' is not defined

**Comment by kenji21** [comment]
hmmm..

    $ ./xibcolor some.xib -l
    #510b1212
    #510b1313

    $ ./xibcolor some.xib "#510b1212" "#FF51FF12"
    From: #510b1212 to: #FF51FF12

    $ ./xibcolor some.xib -l
    #510b1212
    #510b1313

Added a else statement :

    if fromcol and hexv == fromcol.lower():
      ...
    else:
      print "from : " + fromcol + " differs from : " + hexv

    from : #510b1212 differs from : #bb510b0b
    from : #510b1212 differs from : #ff510b0b

**Comment by kenji21** [comment]
Got it, line 35 has alpha at the end

**Comment by ramonpoca** [comment]
Sorry, I'm doing this on the fly while doing other things... :smile: 
Pushed some more sloppy changes... try them

**Comment by ramonpoca** [comment]
If I fuck up some more times you'll end up learning python... (bonus!)

**Comment by kenji21** [comment]
I think there is round issues :

    $ ./xibcolor some.xib -l
    #ba510c12
    #ff510b13

    $ ./xibcolor /Users/kenji/source-cache/somfy-trunk/src/iphone/Alarme/DOAMenuTableViewCell.xib "#ba510c12" "#BB51FF12"
    From: #ba510c12 to: #BB51FF12
    $ ./xibcolor out.storyboard -l
    #ba51ff11
    #ff510b13

ba51ff11 ~ bb51ff12

**Comment by ramonpoca** [comment]
That might be... xibs store floating point values, and obviously #ARGB values are limited in resolution.
Perceptually there should be not much difference, but maybe we should use a "fuzz-factor" when comparing, as it might miss some replacements.

So much for an afternoon hack...

**Comment by kenji21** [comment]
Found it :

    $ ./xibcolor some.xib -l
    0.73
    1.0
    #ba510c12
    #ff510b13
   $ ./xibcolor out.storyboard -l
   0.733333333333
   1.0

By adding a ugly print float(alpha) in listcolors

**Comment by kenji21** [comment]
better with : 

    print "%.8f" % float(alpha)

gives :

    ./xibcolor some.xib -l
    0.730000000000

**Comment by kenji21** [comment]
forgot to show the color in some.xib :

    grep color some.xib
       <color key="textColor" red="0.32156862745098036" green="0.047058823529411764" blue="0.070588235294117646" alpha="0.72999999999999998" colorSpace="calibratedRGB"/>

**Comment by kenji21** [comment]
hmmm... not yet.

0.73*255.0 => 186 => BA as 0.7299999 * 255 does

**Comment by kenji21** [comment]
\o/

    >>> fs="0.733333333333"
    >>> f=float(fs)
    >>> print "%.12f" % f
    0.733333333333
    >>> print "%02x" % round(f*255.0)
    bb
    >>> print "%02x" % (f*255.0)
    ba

**Comment by kenji21** [comment]
Now it's seems to be ok :

    ./xibcolor some.xib -l
    #ff520c13
    #ba520c12
    $ ./xibcolor some.xib "#ba520c12" "#BB51FF12"
    From: #ba520c12 to: #BB51FF12
    $ ./xibcolor out.storyboard -l
    #ff520c13
    #bb51ff12

The patch :

    def clamp(x):
      return max(0, min(int(round(x)), 255))

**Comment by kenji21** [comment]
Apple multiplies the hex value by 255.9999f... o_O

https://developer.apple.com/library/mac/qa/qa1576/_index.html

**Comment by ramonpoca** [comment]
Great.... :neutral_face: 
Can you create a pull request with your changes?

**Comment by kenji21** [comment]
PR sent.

I think it would be interesting to add some unit test for these value rounding issue.

**Comment by ramonpoca** [comment]
Patched.
About UTs, I can't really be bothered. :grin:

**Comment by kenji21** [comment]
Here is the idea behind "coucou" ;-) :

    $ find . -name *.xib -exec xibcolor {} from_to.txt \;
    No colors were replaced in Project/Base.lproj/LaunchScreen.xib
    No colors were replaced in Project/XYZSettingsViewController.xib

**Comment by kenji21** [comment]
new PR done :-)

**Comment by ramonpoca** [comment]
Merged
