### ISSUE TITLE
Some xib can be utf-8

### ISSUE THREAD

**Issue by kenji21** [ramonpoca/ColorTools#8]
Sometimes we write French words in xib files. So Xcode make them utf-8 :

    $ find . -name *.xib -exec file -I {} \;
    ./Project/Base.lproj/LaunchScreen.xib: application/xml; charset=us-ascii
    ./Project/XYZSettingsViewController.xib: application/xml; charset=us-ascii
    ./Project/XYZHomeViewController.xib: application/xml; charset=utf-8

The patch is relatively simple :

    ofile.write(dom.toxml().encode('utf-8'))

**Comment by ramonpoca** [comment]
Does it fail with utf-8 files? The DOM parser should respect the encoding...

**Comment by kenji21** [comment]
I have had :

    Traceback (most recent call last):
      File "./xibcolor", line 78, in <module>
        ofile.write(dom.toxml())
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4741: ordinal not in range(128)

**Comment by kenji21** [comment]
I'll try to reproduce it and upload a xib here

**Comment by ramonpoca** [comment]
I've applied your solution. As any ASCII file will be equivalent to its UTF-8 encoding, this is a no-brainer.

**Comment by kenji21** [comment]
Same issue after using a file for replacements :

    Traceback (most recent call last):
      File "./xibcolor", line 85, in <module>
        ofile.write(dom.toxml())
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4741: ordinal not in range(128)
